site_name: Dio Chacon Wifi API
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google
            show_source: false
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
